In [17]:
import numpy as np
import pandas as pd
from classe_reacteur import Reacteur


In [18]:
from combinaisons import combis, liste_reacs
def gen_data():
    data = []
    for combinaison in combis:
        moment_cree = np.array([0,0,0])
        force_cree = np.array([0,0,0])
        for i, actif in enumerate(combinaison):
            if actif == 1:
                moment_cree = np.add(moment_cree, liste_reacs[i].moment_cree())
                force_cree = np.add(force_cree, liste_reacs[i].force_cree())
        
        data.append(
            pd.DataFrame([{"Combinaison":combinaison, 
                                     "Moment créé [Nm]":moment_cree, 
                                     "Force créée":force_cree}])
                    )
    data = pd.concat(data, ignore_index=True)

    return data

data = gen_data()
print(data)

                                            Combinaison  \
0      (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)   
1      (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1)   
2      (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0)   
3      (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1)   
4      (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0)   
...                                                 ...   
65531  (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1)   
65532  (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0)   
65533  (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1)   
65534  (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0)   
65535  (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)   

                                   Moment créé [Nm]   Force créée  
0                                         [0, 0, 0]     [0, 0, 0]  
1                    [-872.2868000000001, 0.0, 0.0]   [0, 0, 446]  
2                     [0.0, 872.2868000000001, 0.0]   [0, 0, 446]  
3      [-872.286800

In [19]:
print(data["Moment créé [Nm]"][0].max())
print(data["Moment créé [Nm]"][1].max())
print(data["Moment créé [Nm]"][2].max())
print(data["Force créée"][0].max())
print(data["Force créée"][1].max())
print(data["Force créée"][2].max())

0
0.0
872.2868000000001
0
446
446


In [20]:
import numpy as np


In [21]:
def tenseur_des_actifs(tenseur:np.ndarray):
    # actifs = np.zeros_like(tenseur)
    print(type(tenseur))
    shape = (2,) * 16
    coords = np.stack(np.indices(shape), axis=-1)
    return coords

tens = np.meshgrid([0,1], [0,1], [0,1], [0,1], [0,1], [0,1], [0,1], [0,1], [0,1], [0,1], [0,1], [0,1], [0,1], [0,1], [0,1], [0,1])
print(type(tens))
coords = tenseur_des_actifs(tens)

print(coords[0])

<class 'tuple'>
<class 'tuple'>
[[[[[[[[[[[[[[[[0 0 0 ... 0 0 0]
               [0 0 0 ... 0 0 1]]

              [[0 0 0 ... 0 1 0]
               [0 0 0 ... 0 1 1]]]


             [[[0 0 0 ... 1 0 0]
               [0 0 0 ... 1 0 1]]

              [[0 0 0 ... 1 1 0]
               [0 0 0 ... 1 1 1]]]]



            [[[[0 0 0 ... 0 0 0]
               [0 0 0 ... 0 0 1]]

              [[0 0 0 ... 0 1 0]
               [0 0 0 ... 0 1 1]]]


             [[[0 0 0 ... 1 0 0]
               [0 0 0 ... 1 0 1]]

              [[0 0 0 ... 1 1 0]
               [0 0 0 ... 1 1 1]]]]]




           [[[[[0 0 0 ... 0 0 0]
               [0 0 0 ... 0 0 1]]

              [[0 0 0 ... 0 1 0]
               [0 0 0 ... 0 1 1]]]


             [[[0 0 0 ... 1 0 0]
               [0 0 0 ... 1 0 1]]

              [[0 0 0 ... 1 1 0]
               [0 0 0 ... 1 1 1]]]]



            [[[[0 0 0 ... 0 0 0]
               [0 0 0 ... 0 0 1]]

              [[0 0 0 ... 0 1 0]
               [0 0 0 ... 0 1 1

In [27]:
def vectorized_data(tenseur, coordonnées):
    print(tenseur)
    print(coordonnées)
    moment = sum([tenseur.moment_cree() for i in coordonnées if i != 0])
    print(moment)
    # # force = tenseur.force_cree()
    # combinaison = coords

tensor1 = np.empty_like(tens)
shape = np.shape(tensor1)
for idx in np.ndindex(shape):
    tensor1[idx] = liste_reacs


vectorized_data(tenseur=tensor1, coordonnées=coords)


TypeError: int() argument must be a string, a bytes-like object or a real number, not 'list'